language: node_js
node_js:
- node
deploy:
  provider: npm
  email: infrastructure@concreteplatform.com
  api_key:
    secure: B6UVqCa6rpk/Gi3hTwHzfSo3n2xC9VJHQ7s4DInc1a+DS5vVU4BaGHxAy6/V35M1ir6N3RMTH7H+wVjpShJvjoJEhuFvHHPkQ463QLLe/8X2O0w0s2CboAq9D0yMBI9c+Ylkg5DfOXdBPvUWiRkmxu7Df1BsS6QyIssoRUnJoblBF94RdUqHEG5AshvR7vE5pHdOPHzejnQPO/vBamQPcEncWIyb94VXILpcz4CpZxpZDmeKhsG5++tQKABcUp5u2EtrOjWQjiDM+giJKpTrv0W1VBjelYyos52jDz47lG/C0rYN0FiuCFVK/aa5GXHHyldvP2FeGHXlRtn/6LEtDh9u1PVKKOPUg2quqmE6vUeoNg/dBkDsYNbicANU0TaGbWa0SLo5LjSFsZR0KL8hoohqH4tRD5U6AGl+JPLmC6R9bxqxtKA4Py4/jy9geaZsUu6JucuOknN/nQxPJZeEfOJ3HJrZBQfP+X2IUHF+G2cDIMaCiR0zR3DTRYja0Jdadl8q6dTTuEAZzklM2pV09S9Ds41Enz1Innr7SHiqnMm1OYR7yUzPG5ui0uEt/V13QSP48fPGQA+WhBJUdcsvWOoggEm87mDSjpET2MXzrj5cjJpoRHlsEYfAMmKletJ1xvNka8X++NGO1jrlN1Ufq7alM87IHq836d7lsKQYaH0=
  on:
    tags: true
    repo: concrete-cc/jest-mock-express
